kube-prometheus-stack:
  grafana:
    adminPassword: null
    persistence:
      enabled: true
      storageClass: longhorn
  prometheus:
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
