app-template:
  defaultPodOptions:
    hostname: cscosu
    dnsPolicy: "None"
    dnsConfig:
      nameservers:
        - "1.1.1.1"
    annotations:
      io.kubernetes.cri-o.userns-mode: "auto:size=65536"
    runtimeClassName: sysbox-runc
  controllers:
    main:
      replicas: 1
      containers:
        main:
          image:
            repository: ghcr.io/cscosu/vs-workspace
            tag: latest
            pullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 768Mi
            requests:
              cpu: 10m
              memory: 128Mi
  service:
    main:
      ports:
        http:
          port: 8080
