app-template:
  defaultPodOptions:
    hostname: cscosu
    annotations:
      io.kubernetes.cri-o.userns-mode: "auto:size=65536"
    runtimeClassName: sysbox-runc
  controllers:
    main:
      strategy: Recreate
      containers:
        main:
          image:
            repository: ghcr.io/cscosu/vs-workspace
            tag: latest
            pullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 768Mi
  service:
    main:
      ports:
        http:
          port: 8080

  ingress:
    main:
      enabled: true
      hosts:
        - host: workspace.osucyber.club
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
